export const TasksActionTypes = {
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    CLEAR_COMPLETED_TASKS: 'CLEAR_COMPLETED_TASKS',
    SET_CURRENT_TASK: 'SET_CURRENT_TASK'
};